### ISSUE TITLE
false bold on h1

### ISSUE THREAD

**Issue by varffs** [interglobalvision/material-fair-com#104]
![screen shot 2016-08-05 at 15 07 53](https://cloud.githubusercontent.com/assets/845186/17449163/6a7d8900-5b1e-11e6-97f9-ebf4d03a4df7.png)

Possibly also on other headings

**Comment by mikeyrayvon** [comment]
this isnt a false bold. its Stanley Poster.  see `/fonts.styl`

**Comment by varffs** [comment]
It is. Force set the weight to normal and toggle in inspector

**Comment by varffs** [comment]
Oh it looks false tho? I toggled between `font-weight: normal` and not and it looked weird

**Comment by mikeyrayvon** [comment]
if you set the weight to normal it switches to stanley bold

**Comment by varffs** [comment]
Ok sorry. Just the rendering of it looks off. I didn't realise there was an extrabold weird to be used

**Comment by mikeyrayvon** [comment]
![screen shot 2016-08-05 at 1 30 44 pm](https://cloud.githubusercontent.com/assets/7727722/17449652/dec0e63a-5b10-11e6-8ea4-1cb259a03d99.png)
youre right it looks a lil off
