### ISSUE TITLE
mailing list email margin bottom

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/material-fair-com#119]
on mobile

**Comment by varffs** [comment]
what about it!?

**Comment by mikeyrayvon** [comment]
![screen shot 2016-08-11 at 3 52 17 pm](https://cloud.githubusercontent.com/assets/7727722/17607601/9dd9ed2c-5fdb-11e6-8bf6-8b1638d169d1.png)

**Comment by varffs** [comment]
you can just give the input element a margin bottom?

**Comment by mikeyrayvon** [comment]
actually i should take the `size` attribute off of the input elem. just tried. that fixes it
